add Ab:RBD analysis scripts
choderalab/rbd-ab-contact-analysis pull request #3
Opened 2021-06-21 20:28 UTC by glass-w

This PR adds analysis scripts used for Ab:RBD systems

TODO

- [x] add analysis scripts
- [x] add yaml files for plotting
- [x] update README

2021-06-23 15:31 UTC, zhang-ivy requested changes

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +Below are exmaples of how to use analysis scripts to analyse the dataset for F@H data in [DOI link]. It is recommened to run each of these scripts in separate directories.
```suggestion
Below are examples of how to use analysis scripts to analyse the dataset for F@H data in [DOI link]. It is recommended to run each of these scripts in separate directories.
```

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +`analyze_antibody_rbd_contacts.py` can be used to generate a series of `.pkl` files containing an N x M x No. frames array of distances between heavy atoms at the RBD:Ab interface.
can you define N and M here?

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +* `system.pdb` should contain no solvent.
```suggestion
* `system.pdb` is a PDB of the RBD:antibody without waters, but with ions.
```

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +python analyze_antibody_rbd_contacts.py -mutant WT -pdb_file system.pdb -traj_path path/to/traj/ -fah_project_code 17341 -chain_info_file chain_info_S2H97_RBD.yaml -run_number 0 -discard_time 100
can you define what `-chain_info_file` and `-run_number` and `-discard_time` correspond to?

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +python make_hmaps.py -data count_chain1.pkl count_chain2.pkl -save_path path/to/save/plots -ab_name S2H97 -custom_residues_file s2h97_ab_custom_residues.yaml
can you define what `-custom_residues_file` corresponds to?

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +python analyze_antibody_rbd_contacts.py -mutant WT -pdb_file system.pdb -traj_path path/to/traj/ -fah_project_code 17341 -chain_info_file chain_info_S2H97_RBD.yaml -run_number 0 -discard_time 100
And also specify that there are 5 RUNs for each project, so we ran this command on each of the 5 RUNs separately. And that we used a discard time of 100 for all analysis jobs.

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +For example, analysing the F@H `17341` project (S2H97:Ab):
```suggestion
For example, analysing the F@H `17347` project (RBD:S309):
```

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +For example, analysing the F@H `17341` project (S2H97:Ab):
Can you add a line above this that says something like: 
Project numbers:
RBD:S309 - 17341
RBD:S2H97 - 17347

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +python analyze_antibody_rbd_contacts.py -mutant WT -pdb_file system.pdb -traj_path path/to/traj/ -fah_project_code 17341 -chain_info_file chain_info_S2H97_RBD.yaml -run_number 0 -discard_time 100
```suggestion
python analyze_antibody_rbd_contacts.py -mutant WT -pdb_file system.pdb -traj_path path/to/traj/ -fah_project_code 17341 -chain_info_file chain_info_S309_RBD.yaml -run_number 0 -discard_time 100
```

2021-06-23 15:31 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +python make_hmaps.py -data count_chain1.pkl count_chain2.pkl -save_path path/to/save/plots -ab_name S2H97 -custom_residues_file s2h97_ab_custom_residues.yaml
```suggestion
python make_hmaps.py -data count_chain1.pkl count_chain2.pkl -save_path path/to/save/plots -ab_name S2H97 -custom_residues_file s309_ab_custom_residues.yaml
```

2021-06-23 15:33 UTC, zhang-ivy commented
Also, just noticed that in the main README, the manifest section says `02_analysis/` -- could you either change the name of the directory in this PR or change the name in the main README? up to you which name you want to keep!

2021-06-23 15:35 UTC, zhang-ivy commented
Also, I noticed main README `02_analysis` part says `analysis script` instead of `scripts`.. could you update that as well?

2021-06-23 15:40 UTC, zhang-ivy commented
Also, I noticed the main README has a typo near the BAOAB langevin integrator. Need to replace `78` with the reference (Leimkuhler and Matthews, 2013)[https://doi.org/10.1063/1.4802990]

2021-06-23 15:40 UTC, zhang-ivy commented
I can make all the main README changes if you want, just let me know when you're done fixing this PR!

2021-06-23 16:35 UTC, glass-w commented
@zhang-ivy I've addressed your comments and updated the main README to have `02_analysis_scripts`

2021-06-23 16:38 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +* The `-discard_time` flag specifies how much time to discard for a particular CLONE before starting contact analysis.
```suggestion
* The `-discard_time` flag specifies how much time (ns) to discard for a particular CLONE before starting contact analysis.
```

2021-06-23 16:38 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +For this project there were a total of 5 RUNs, so the above script was ran on each RUN separately. Additioanlly a `-discard_time` of 100 ns was applied
```suggestion
For this project there were a total of 5 RUNs, so the above script was ran on each RUN separately. Additionally a `-discard_time` of 100 ns was applied
```

2021-06-23 16:42 UTC, zhang-ivy commented on 02_analysis_scripts/README.md
> +* The `-custom_residues_file` should point to a YAML file containing the system type (e.g. WT). See `s2h97_ab_custom_residues.yaml` for an example.
I think you mean:
```suggestion
* The `-custom_residues_file` should point to a YAML file containing the RBD residues for which to compute the % contribution to total interface close contacts. See `s2h97_ab_custom_residues.yaml` for an example.
```

2021-06-24 12:37 UTC, zhang-ivy approved these changes

2021-06-24 12:38 UTC, merged